volumes:
  todo_app-postgres-data:
  todo_app-redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mtorreao/todo_app_rails
    ports:
      - "3000:3000"
    environment:
      - "RAILS_ENV=production"
      - "RAILS_MASTER_KEY=${SERVICE_RAILS_MASTER_KEY}"
      
  redis:
    image: "redis:7"
    volumes:
      - "todo_app-redis-data:/data"
    command:
      - redis-server
      - "--maxmemory-policy"
      - noeviction
    # ports:
      # - "6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 5s
      timeout: 10s
      retries: 20
